version: "3.7"

services:
  pyspark:
    image: quay.io/jupyter/pyspark-notebook
    container_name: pyspark-quick-start
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    working_dir: /home/jovyan/work